[build]
  base = "e-bike-comparison-frontend"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"

[build.environment]
  NODE_VERSION = "14" # or whichever version you're using

# If you need to specify a custom API URL
# [context.production.environment]
#   REACT_APP_API_URL = "https://your-api-url.com"
